### ISSUE TITLE
Screen error

### ISSUE THREAD

**Issue by sturlahallas** [MisterEmm/pingdoorbell#1]
NVM: Happens when you start in an SSH-terminal. Not an issue.

Hi, and thanks for a brilliant project. I have one issue with the PiNG.py script, and it throws this error:

```
Traceback (most recent call last):
  File "/home/pi/PiNG.py", line 10, in <module>
    m = PyMouse()
  File "/home/pi/.local/lib/python3.7/site-packages/pymouse/x11.py", line 86, in __init__
    self.display = Display(display)
  File "/home/pi/.local/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/pi/.local/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/pi/.local/lib/python3.7/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/home/pi/.local/lib/python3.7/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/home/pi/.local/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

I would assume it's about setting the right screen somewhere/pretending to be HDMI. Cannot find documentation on how to do this, so I'm asking for your help. Thank you.

**Comment by MisterEmm** [comment]
Hi sorry for the delayed response, just back from holiday - glad you got it sorted.

**Comment by getgray** [comment]
What's the cure?
